music/urls.py
#will contain just the urls of my music compartment
from django.conf.urls import url
from . import views #. is for current directory's views

app_name="music"


urlpatterns = [
    # /music/
    url(r'^$',views.IndexView.as_view(),name='index'), #default section in music

    #/music/71<album_id>/            (ID)(details waala tab)
    url(r'^(?P<pk>[0-9]+)/$',views.DetailsView.as_view(),name="detail"), #keyword used in index

    # /music/71<album_id>/favourite
    #url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favorite, name="favorite"),  # keyword used in index

    #music/album/add/
    url(r'album/add/$',views.AlbumCreate.as_view(),name="album-add"),

    #music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name="album-update"),

    #music/album/2/delete/
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name="album-delete"),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.urls import reverse
#contains blueprint
#ID 1 for below class
class Album(models.Model):
    #artist is basically a column in db
    artist = models.CharField(max_length=250) #artist name is character for 250 lengths
    album_title=models.CharField(max_length=500)
    genre=models.CharField(max_length=100)
    album_logo=models.CharField(max_length=1000)

    def get_absolue_urll(self):
       return reverse("music:detail",kwargs={'pk':self.pk}) #music/2

    #type all the details inside the interactive shell
    def __str__(self):#string representation of album
        return self.album_title +"-"+ self.artist
#Id 2
class Song(models.Model):
    #ForeignKey is basically a id here it is 1
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    is_favorite =models.BooleanField(default=False)
    def __str__(self):#string representation of album
        return self.song_title

music/views.py
#from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy
from . models import Album

class IndexView(generic.ListView):
    template_name="music/index.html"
    context_object_name="all_albums"
    def get_queryset(self):
        return Album.objects.all()

class DetailsView(generic.DetailView):
    model=Album
    template_name="music/detail.html"

class AlbumCreate(CreateView):
    model=Album
    fields=["artist","album_title","genre","album_logo"]

class AlbumUpdate(UpdateView):
    model=Album
    fields=["artist","album_title","genre","album_logo"]

class AlbumDelete(DeleteView):
    model=Album
    success_url= reverse_lazy("music:index")#basically used to redirect to old page after deleting

music/templates/music/album_form.html
<!-- Form for storing elements -->
{% extends "music/base.html" %}
{% block title %}Add a new Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class=""container-fluid">
    <div class="row">
        <div class=""col-sm-12 col-md-7">
           <div class="panel panel-default">
                <div class="panel-body">


                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include "music/form-template.html" %}
                        <div class="form=group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>


                </div>
           </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/base.html
<!-- Base file for all pages-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?fammily=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/styles.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

      <!-- Logo/Header-->
      <div class="navbar-header">
         <button type="bottom" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar"><!-- if not more room-->
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
         </button>
        <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
      </div>

      <!-- Items-->
       <div class="collapse navbar-collapse" id="topNavBar">
          <ul class="nav navbar-nav">
             <li class="active">
                <a href="{% url 'music:index' %}">
                   <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                </a>

             </li>
             <li class="">
                <a href="#">
                   <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                </a>
             </li>
          </ul>
          <form class="navbar-form navbar-lef" role="search" method="get" action="#">
             <div class="form-group">
                  <input type="text" class="form-control" name="q" value="">
             </div>
             <button type="submit" class="btn btn-default">Search</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
             <li class="">
                <a href="{% url 'music:album-add' %}">
                   <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                </a>
             </li>
             <li class="">
                <a href="#">
                   <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                </a>
             </li>
          </ul>

       </div>


    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details {% endblock %}

{% block body %}
    <img src="{{ album.album_logo }}" height="100" width="200">

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>
    {% for song in album.song_set.all %}
                {{ song.song_title }}
                {% if song.is_favorite %}
                    <img src="http://i.imgur.com/b9b13Rd.png" />
                {% endif %}
        <br>
        {% endfor %}
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}